"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";

export default function AuthPage(){
  const [sent,setSent]=useState(false);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault(); setSent(true)}
  return <main className="wrap section topspace"><div className="grid grid2"><section><p className="kicker">Host access</p><h1 className="big">Create a host account before the guest changes their mind.</h1><p className="lead" style={{fontSize:18}}>GapStay is built for owners who need calendar certainty. The production flow is email auth first, then Stripe, then the host dashboard.</p><div className="card pad" style={{marginTop:24}}><h2>What auth unlocks</h2><ul className="list"><li>Saved properties and listings.</li><li>Reusable inquiry pages.</li><li>Host dashboard and lead history.</li><li>Payment-gated publishing when Stripe is enabled.</li></ul></div></section><section className="card pad" style={{alignSelf:"start"}}>{sent?<div><p className="kicker">Account staged</p><h2 className="big">You are ready to analyze a gap.</h2><p className="muted">For this production MVP, the form captures the account intent and moves the host into the analyzer. Supabase auth can be switched on behind this screen.</p><Link className="darkpill" href="/host">Continue</Link></div>:<form onSubmit={submit} className="grid"><label><span className="label">Name</span><input className="input" name="name" required/></label><label><span className="label">Email</span><input className="input" type="email" name="email" required/></label><label><span className="label">How many listings?</span><select className="input" name="count"><option>1 listing</option><option>2-5 listings</option><option>6+ listings</option></select></label><button className="darkpill" type="submit">Create host account</button><p className="small">No password wall in the MVP. The goal is to get hosts to the value moment fast.</p></form>}</section></div></main>
}
