"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { analyzeGap, money, prettyDate } from "../../lib/pricing";
import { saveListingRemote, type Listing } from "../../lib/store";

export default function HostPage(){
  const [form,setForm]=useState({sourceUrl:"",startDate:"2026-07-03",endDate:"2026-08-14",nightlyTarget:"210",expectedOccupancy:"43",cleaningFee:"195",market:"balanced",title:"Quiet furnished stay with workspace",city:"Marco Island",state:"FL",propertyType:"Condo",bedrooms:"2",bathrooms:"2",hostName:"Host",ownerEmail:"",description:"A furnished mid-term stay with fast Wi-Fi, kitchen, laundry, parking, and transparent all-in pricing."});
  const [listing,setListing]=useState<Listing|null>(null);
  const [saving,setSaving]=useState(false);
  function update(key:string,value:string){setForm(prev=>({...prev,[key]:value}))}
  function useSourceUrl(){try{const u=new URL(form.sourceUrl);const checkIn=u.searchParams.get("check_in");const checkOut=u.searchParams.get("check_out");const isAirbnb=u.hostname.includes("airbnb");const isVrbo=u.hostname.includes("vrbo");setForm(prev=>({...prev,startDate:checkIn||prev.startDate,endDate:checkOut||prev.endDate,title:isAirbnb?"Airbnb furnished stay offer":isVrbo?"VRBO furnished stay offer":prev.title,description:`Source listing: ${form.sourceUrl}\n\nA furnished stay offer created from the host's existing listing link. Add the strongest property details before publishing.`}))}catch{alert("Paste a valid Airbnb or VRBO listing URL.")}}
  async function submit(e:FormEvent){
    e.preventDefault();
    setSaving(true);
    const analysis=analyzeGap({startDate:form.startDate,endDate:form.endDate,nightlyTarget:Number(form.nightlyTarget),expectedOccupancy:Number(form.expectedOccupancy),cleaningFee:Number(form.cleaningFee),market:form.market as any});
    const next:Listing={id:`listing-${Date.now().toString(36)}`,title:form.title,city:form.city,state:form.state,propertyType:form.propertyType,bedrooms:Number(form.bedrooms),bathrooms:Number(form.bathrooms),hostName:form.hostName,description:form.description,amenities:["Fast Wi-Fi","Workspace","Kitchen","Laundry","Parking","Utilities included"],rules:["No smoking","Normal checkout cleaning","Quiet hours after 10 PM"],analysis};
    const saved=await saveListingRemote(next, form.ownerEmail || undefined);
    setListing(saved);
    setSaving(false);
  }
  return <main className="wrap section topspace"><div className="grid grid2">
    <div><p className="kicker">Free gap scan</p><h1 className="big">Paste a listing link or enter the gap manually.</h1><p className="muted">Already on Airbnb or VRBO? Paste the listing URL first. GapStay will use the dates in the link when available, then you can finish the details needed to analyze the gap.</p>
      <div className="card pad grid" style={{marginTop:24, marginBottom:18}}><Field label="Airbnb or VRBO listing URL" value={form.sourceUrl} onChange={v=>update("sourceUrl",v)} required={false}/><button className="pill" type="button" onClick={useSourceUrl}>Use this listing link</button><p className="small">MVP note: this pulls usable dates from the URL when present. Full listing import comes later.</p></div>
      <form onSubmit={submit} className="card pad grid" style={{marginTop:24}}>
        <div className="grid grid2"><Field label="Start date" type="date" value={form.startDate} onChange={v=>update("startDate",v)}/><Field label="End date" type="date" value={form.endDate} onChange={v=>update("endDate",v)}/></div>
        <div className="grid grid3"><Field label="Nightly target" value={form.nightlyTarget} onChange={v=>update("nightlyTarget",v)}/><Field label="Expected occupancy %" value={form.expectedOccupancy} onChange={v=>update("expectedOccupancy",v)}/><Field label="Cleaning fee" value={form.cleaningFee} onChange={v=>update("cleaningFee",v)}/></div>
        <label><span className="label">Market</span><select className="input" value={form.market} onChange={e=>update("market",e.target.value)}><option value="soft">Soft / lots of vacancy</option><option value="balanced">Balanced</option><option value="hot">Hot / scarce inventory</option></select></label>
        <div className="grid grid2"><Field label="Listing title" value={form.title} onChange={v=>update("title",v)}/><Field label="Host name" value={form.hostName} onChange={v=>update("hostName",v)}/></div>
        <Field label="Host email" type="email" value={form.ownerEmail} onChange={v=>update("ownerEmail",v)}/>
        <div className="grid grid3"><Field label="City" value={form.city} onChange={v=>update("city",v)}/><Field label="State" value={form.state} onChange={v=>update("state",v)}/><Field label="Type" value={form.propertyType} onChange={v=>update("propertyType",v)}/></div>
        <div className="grid grid2"><Field label="Bedrooms" value={form.bedrooms} onChange={v=>update("bedrooms",v)}/><Field label="Bathrooms" value={form.bathrooms} onChange={v=>update("bathrooms",v)}/></div>
        <label><span className="label">Description</span><textarea className="input textarea" value={form.description} onChange={e=>update("description",e.target.value)}/></label>
        <button className="darkpill" type="submit">{saving?"Saving...":"Run free gap scan"}</button>
      </form>
    </div>
    <div className="card pad" style={{alignSelf:"start",position:"sticky",top:96}}>{listing?<Result listing={listing}/>:<p className="muted">Your scan will appear here. It will compare likely short-term revenue against a furnished-stay offer, then show timing status and a sample marketing page.</p>}</div>
  </div></main>
}
function Field({label,value,onChange,type="text",required=true}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label><span className="label">{label}</span><input className="input" type={type} value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>}
function timingCall(startDate:string,nights:number){const days=Math.round((new Date(`${startDate}T12:00:00`).getTime()-Date.now())/86400000);if(days>90)return{label:"Watch",text:"Too early to act. Keep tracking it, but this gap is long enough to keep on the radar."};if(days>60)return{label:"Package now",text:"This is the backup-offer window. Keep Airbnb live, but build the furnished-stay offer before monthly guests move on."};if(days>45)return{label:"Act now",text:"Start sharing the offer. Monthly guests are still possible, but the window is closing."};if(days>30)return{label:"Late",text:"You can still try, but waiting has already reduced the monthly-stay pool."};return{label:"Salvage",text:"Under 30 days is usually discounted nightly, local outreach, or partial-stay salvage."}}
function Result({listing}:{listing:Listing}){const a=listing.analysis;const t=timingCall(a.startDate,a.nights);return <div><p className="kicker">GapStay recommendation</p><h2 className="big">{t.label}</h2><p className="muted">{prettyDate(a.startDate)} - {prettyDate(a.endDate)} · {a.nights} nights · suggested furnished-stay offer {money(a.recommendedTotal)}</p><div className="metric" style={{marginTop:18}}><b>Best next move</b><p className="small">{t.text}</p></div><div className="metric" style={{marginTop:14}}><b>Keep the upside. Add a fallback.</b><p className="small">Keep Airbnb live while you test this furnished-stay offer. Only block the dates when a renter is ready.</p></div><div className="result" style={{marginTop:18}}><div className="stat"><span>Best-case nightly</span><strong>{money(a.fullNightRevenue)}</strong></div><div className="stat"><span>Likely nightly</span><strong>{money(a.likelyShortTermRevenue)}</strong></div><div className="stat"><span>Fallback offer</span><strong>{money(a.recommendedTotal)}</strong></div><div className="stat"><span>Saved turns</span><strong>{money(a.turnoverSavings)}</strong></div></div><ul className="list">{a.explanation.map(x=><li key={x}>{x}</li>)}<li>Post the furnished-stay offer where temporary renters actually look.</li><li>Use Calendar Watch only if you want future gaps monitored.</li></ul><div className="actions"><Link className="darkpill" href="/pricing">Publish this offer - $19</Link><Link className="pill" href={`/listing/${listing.id}`}>Preview offer</Link></div><div className="card pad" style={{marginTop:18}}><h3>Want this for future gaps?</h3><p className="muted">Calendar Watch is early access assisted monitoring for hosts who want future gaps watched.</p><div className="actions"><Link className="pill" href="/pricing">See watch plans</Link></div></div></div>}
