"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { getInquiriesRemote, getListingsRemote, type Inquiry, type Listing } from "../../lib/store";
import { money, prettyDate } from "../../lib/pricing";
import { getSupabaseBrowserClient } from "../../lib/supabase";

const sampleCalendar = Array.from({length:180},(_,i)=>{const m=i%60;return m<10?"AIRBNB":m<20?"WATCH":"FURNISHED"});

export default function DashboardPage(){
  const [listings,setListings]=useState<Listing[]>([]);
  const [inquiries,setInquiries]=useState<Inquiry[]>([]);
  const [error,setError]=useState("");
  const [userEmail,setUserEmail]=useState<string|null>(null);const [checkingAuth,setCheckingAuth]=useState(true);
  useEffect(()=>{let alive=true;const client=getSupabaseBrowserClient();async function load(){const {data}=client?await client.auth.getSession():{data:{session:null}};if(!alive)return;if(!data.session){setCheckingAuth(false);return}setUserEmail(data.session.user.email||"");try{const [l,i]=await Promise.all([getListingsRemote(),getInquiriesRemote()]);if(alive){setListings(l);setInquiries(i)}}catch(error){if(alive)setError(error instanceof Error?error.message:"Could not load dashboard.")}finally{if(alive)setCheckingAuth(false)}}void load();return()=>{alive=false}},[]);
  if(checkingAuth)return <main className="wrap section topspace"><div className="card pad"><p className="muted">Loading your dashboard…</p></div></main>;
  if(!userEmail)return <main className="wrap section topspace"><div className="card pad authCard"><p className="kicker">Calendar CFO dashboard</p><h1 className="big">See what GapStay gives every host.</h1><p className="muted">The dashboard is where your AIRBNB / WATCH / FURNISHED calendar plan lives. Sign in to save plans, monitor properties, receive alerts, and track furnished-stay inquiries.</p><SampleCalendar/><div className="actions"><Link className="darkpill" href="/auth?next=/dashboard">Sign in</Link><Link className="pill" href="/host">Build calendar plan</Link></div></div></main>;
  return <main className="wrap section topspace"><p className="kicker">Calendar CFO dashboard</p><h1 className="big">Your property plan lives here.</h1><p className="muted">Saved AIRBNB / WATCH / FURNISHED plans, monitored properties, alerts, furnished-stay offers, and renter inquiries.</p>
    <div className="actions"><span className="small">Signed in as {userEmail}</span><button className="manualLink buttonLink" onClick={async()=>{await getSupabaseBrowserClient()?.auth.signOut();location.reload()}}>Sign out</button></div>
    {error?<div className="errorBox">{error}</div>:null}<SampleCalendar/>
    <section className="section" style={{paddingTop:28}}><div className="heroCardTop"><h2>Saved calendar plans and furnished-stay offers</h2><Link className="darkpill" href="/host">Build calendar plan</Link></div>{listings.length===0?<div className="card pad" style={{marginTop:16}}><h3>No saved plans yet.</h3><p className="muted">Paste your Airbnb or VRBO listing URL to generate an AIRBNB / WATCH / FURNISHED calendar plan.</p><Link className="darkpill" href="/host">Build calendar plan</Link></div>:<div className="grid" style={{marginTop:16}}>{listings.map(l=><div className="card pad" key={l.id}><div className="heroCardTop"><div><p className="kicker">{publicationLabel(l)}</p><h3>{l.title}</h3><p className="muted">{l.city}, {l.state} · {prettyDate(l.analysis.startDate)} - {prettyDate(l.analysis.endDate)}</p></div><div style={{textAlign:"right"}}><b style={{fontSize:28}}>{money(l.analysis.recommendedTotal)}</b><p className="small">Furnished offer · {money(l.analysis.monthlyEquivalent)}/mo</p></div></div><div className="actions"><Link className="pill" href={`/listing/${l.id}`}>Open offer</Link></div></div>)}</div>}</section>
    <section><h2>Renter inquiries</h2>{inquiries.length===0?<div className="card pad"><p className="muted">No inquiries yet. Published furnished-stay offers collect renter requests here.</p></div>:<div className="grid">{inquiries.map(inquiry=><InquiryCard key={inquiry.id} inquiry={inquiry}/>)}</div>}</section>
  </main>
}

function SampleCalendar(){return <section className="card pad" style={{margin:"22px 0"}}><div className="heroCardTop"><div><p className="kicker">Sample calendar plan</p><h2>Marco Island 2BR · next 6 months</h2><p className="muted">This is the product: a simple calendar showing which dates belong on Airbnb, which need watching, and which should be marketed as furnished housing.</p></div><div className="result"><SmallLegend color="#7ecfaa" label="AIRBNB"/><SmallLegend color="#ead27b" label="WATCH"/><SmallLegend color="#e87b6a" label="FURNISHED"/></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(30,1fr)",gap:4,marginTop:18}}>{sampleCalendar.map((d,i)=><span key={i} title={`Day ${i+1}: ${d}`} style={{height:14,borderRadius:3,background:d==="AIRBNB"?"#7ecfaa":d==="WATCH"?"#ead27b":"#e87b6a"}} />)}</div><div className="grid grid3" style={{marginTop:20}}><MiniRange dates="Jan 1 – Mar 14" rec="FURNISHED" text="Furnished-rental economics beat scattered nightly demand."/><MiniRange dates="Mar 15 – Apr 6" rec="AIRBNB" text="Peak-season demand supports holding for nightly bookings."/><MiniRange dates="Apr 7 – Apr 28" rec="WATCH" text="Leave on Airbnb for now. Re-check before committing."/></div></section>}
function SmallLegend({color,label}:{color:string;label:string}){return <span className="small" style={{display:"inline-flex",alignItems:"center",gap:6,marginRight:10}}><span style={{width:10,height:10,borderRadius:99,background:color}}/>{label}</span>}
function MiniRange({dates,rec,text}:{dates:string;rec:string;text:string}){return <div className="stat"><span>{dates}</span><strong>{rec}</strong><p className="small" style={{margin:"8px 0 0"}}>{text}</p></div>}
function publicationLabel(listing:Listing){if(listing.publishStatus!=="published") return "Plan preview";if(!listing.paidUntil) return "Published furnished-stay offer";const days=Math.max(0,Math.ceil((new Date(listing.paidUntil).getTime()-Date.now())/86400000));return `Published offer · ${days} ${days===1?"day":"days"} remaining`}
function InquiryCard({inquiry}:{inquiry:Inquiry}){const subject=encodeURIComponent("Your furnished-stay inquiry");const body=encodeURIComponent(`Hi ${inquiry.name},\n\nThanks for your inquiry. I’d be happy to discuss the furnished stay and your dates.\n\n`);return <article className="card pad"><div className="heroCardTop"><div><p className="kicker">{inquiry.reason||"New inquiry"}</p><h3>{inquiry.name}</h3><p className="small">Received {new Date(inquiry.createdAt).toLocaleDateString()}</p></div><div className="actions"><a className="darkpill" href={`mailto:${inquiry.email}?subject=${subject}&body=${body}`}>Reply by email</a>{inquiry.phone?<a className="pill" href={`tel:${inquiry.phone}`}>Call {inquiry.phone}</a>:null}</div></div><p className="muted">{inquiry.message}</p><a className="manualLink" href={`mailto:${inquiry.email}`}>{inquiry.email}</a></article>}
