"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { getInquiriesRemote, getListingsRemote, type Inquiry, type Listing } from "../../lib/store";
import { money, prettyDate } from "../../lib/pricing";
import { getSupabaseBrowserClient } from "../../lib/supabase";

const months=[
  {name:"Jan",rec:"FURNISHED",why:"Low visitor demand. Use a 30+ day furnished renter.",air:"$900",furnished:"$3,900"},
  {name:"Feb",rec:"FURNISHED",why:"Short stays are unlikely to fill enough nights.",air:"$1,100",furnished:"$3,900"},
  {name:"Mar",rec:"WATCH",why:"Leave on Airbnb, but switch if still open 45 days out.",air:"$2,600",furnished:"$3,900"},
  {name:"Apr",rec:"AIRBNB",why:"Spring holidays and NYC/Long Island visits support nightly stays.",air:"$4,800",furnished:"$3,900"},
  {name:"May",rec:"WATCH",why:"Borderline. Watch graduations, weddings, and weekend demand.",air:"$3,400",furnished:"$3,900"},
  {name:"Jun",rec:"AIRBNB",why:"Summer Long Island demand supports nightly bookings.",air:"$5,200",furnished:"$4,100"},
  {name:"Jul",rec:"AIRBNB",why:"Peak summer and July 4th demand. Hold for nightly bookings.",air:"$6,400",furnished:"$4,100"},
  {name:"Aug",rec:"AIRBNB",why:"Peak summer. Airbnb upside is worth the risk.",air:"$6,100",furnished:"$4,100"},
  {name:"Sep",rec:"WATCH",why:"Labor Day is strong. The rest of the month may need a switch.",air:"$3,700",furnished:"$4,000"},
  {name:"Oct",rec:"FURNISHED",why:"Not enough demand to gamble on scattered weekends.",air:"$1,800",furnished:"$3,900"},
  {name:"Nov",rec:"WATCH",why:"Thanksgiving may work. Watch the rest of the month.",air:"$2,900",furnished:"$3,900"},
  {name:"Dec",rec:"WATCH",why:"Christmas week can work. Avoid leaving the whole month to chance.",air:"$3,200",furnished:"$3,900"}
];

export default function DashboardPage(){
  const [listings,setListings]=useState<Listing[]>([]);
  const [inquiries,setInquiries]=useState<Inquiry[]>([]);
  const [error,setError]=useState("");
  const [userEmail,setUserEmail]=useState<string|null>(null);const [checkingAuth,setCheckingAuth]=useState(true);
  useEffect(()=>{let alive=true;const client=getSupabaseBrowserClient();async function load(){const {data}=client?await client.auth.getSession():{data:{session:null}};if(!alive)return;if(!data.session){setCheckingAuth(false);return}setUserEmail(data.session.user.email||"");try{const [l,i]=await Promise.all([getListingsRemote(),getInquiriesRemote()]);if(alive){setListings(l);setInquiries(i)}}catch(error){if(alive)setError(error instanceof Error?error.message:"Could not load dashboard.")}finally{if(alive)setCheckingAuth(false)}}void load();return()=>{alive=false}},[]);
  if(checkingAuth)return <main className="wrap section topspace"><div className="card pad"><p className="muted">Loading your dashboard…</p></div></main>;
  if(!userEmail)return <main className="wrap section topspace"><div className="card pad authCard"><p className="kicker">Calendar CFO dashboard</p><h1 className="big">See what GapStay gives every host.</h1><p className="muted">The dashboard is where your AIRBNB / WATCH / FURNISHED calendar plan lives.</p><SampleCalendar/><div className="actions"><Link className="darkpill" href="/auth?next=/dashboard">Sign in</Link><Link className="pill" href="/host">Build calendar plan</Link></div></div></main>;
  return <main className="wrap section topspace"><p className="kicker">Calendar CFO dashboard</p><h1 className="big">Your property plan lives here.</h1><p className="muted">Saved calendar plans, monitored properties, alerts, furnished-stay offers, and renter inquiries.</p><div className="actions"><span className="small">Signed in as {userEmail}</span><button className="manualLink buttonLink" onClick={async()=>{await getSupabaseBrowserClient()?.auth.signOut();location.reload()}}>Sign out</button></div>{error?<div className="errorBox">{error}</div>:null}<SampleCalendar/><section className="section" style={{paddingTop:28}}><div className="heroCardTop"><h2>Saved plans and offers</h2><Link className="darkpill" href="/host">Build calendar plan</Link></div>{listings.length===0?<div className="card pad" style={{marginTop:16}}><h3>No saved plans yet.</h3><p className="muted">Paste your Airbnb or VRBO listing URL to generate a calendar plan.</p><Link className="darkpill" href="/host">Build calendar plan</Link></div>:<div className="grid" style={{marginTop:16}}>{listings.map(l=><div className="card pad" key={l.id}><div className="heroCardTop"><div><p className="kicker">{publicationLabel(l)}</p><h3>{l.title}</h3><p className="muted">{l.city}, {l.state} · {prettyDate(l.analysis.startDate)} - {prettyDate(l.analysis.endDate)}</p></div><div style={{textAlign:"right"}}><b style={{fontSize:28}}>{money(l.analysis.recommendedTotal)}</b><p className="small">Furnished offer · {money(l.analysis.monthlyEquivalent)}/mo</p></div></div><div className="actions"><Link className="pill" href={`/listing/${l.id}`}>Open offer</Link></div></div>)}</div>}</section><section><h2>Renter inquiries</h2>{inquiries.length===0?<div className="card pad"><p className="muted">No inquiries yet.</p></div>:<div className="grid">{inquiries.map(inquiry=><InquiryCard key={inquiry.id} inquiry={inquiry}/>)}</div>}</section></main>
}
function color(rec:string){return rec==="AIRBNB"?"#7ecfaa":rec==="WATCH"?"#ead27b":"#e87b6a"}
function SampleCalendar(){return <section className="card pad" style={{margin:"22px 0"}}><div className="heroCardTop"><div><p className="kicker">Detailed sample plan</p><h2>Massapequa, NY house · next 12 months</h2><p className="muted">Plain-English answer for each month: keep it on Airbnb, watch it, or market it as a furnished rental.</p></div><div className="result"><SmallLegend color="#7ecfaa" label="AIRBNB"/><SmallLegend color="#ead27b" label="WATCH"/><SmallLegend color="#e87b6a" label="FURNISHED"/></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:16,marginTop:18}}>{months.map(m=><div key={m.name} className="stat" style={{borderLeft:`6px solid ${color(m.rec)}`,minWidth:0}}><span>{m.name}</span><strong style={{fontSize:16,whiteSpace:"nowrap",lineHeight:1.1}}>{m.rec}</strong><p className="small" style={{margin:"8px 0"}}>{m.why}</p><p className="small" style={{margin:0}}>Airbnb likely: <b>{m.air}</b><br/>Furnished: <b>{m.furnished}</b></p></div>)}</div><div className="successBox" style={{marginTop:18}}><strong>Next action:</strong> Keep June–August on Airbnb. Start marketing January, February, and October as furnished rentals. Watch March, May, September, November, and December instead of guessing.</div></section>}
function SmallLegend({color,label}:{color:string;label:string}){return <span className="small" style={{display:"inline-flex",alignItems:"center",gap:6,marginRight:10,whiteSpace:"nowrap"}}><span style={{width:10,height:10,borderRadius:99,background:color}}/>{label}</span>}
function publicationLabel(listing:Listing){if(listing.publishStatus!=="published") return "Plan preview";if(!listing.paidUntil) return "Published furnished-stay offer";const days=Math.max(0,Math.ceil((new Date(listing.paidUntil).getTime()-Date.now())/86400000));return `Published offer · ${days} ${days===1?"day":"days"} remaining`}
function InquiryCard({inquiry}:{inquiry:Inquiry}){const subject=encodeURIComponent("Your furnished-stay inquiry");const body=encodeURIComponent(`Hi ${inquiry.name},\n\nThanks for your inquiry. I’d be happy to discuss the furnished stay and your dates.\n\n`);return <article className="card pad"><div className="heroCardTop"><div><p className="kicker">{inquiry.reason||"New inquiry"}</p><h3>{inquiry.name}</h3><p className="small">Received {new Date(inquiry.createdAt).toLocaleDateString()}</p></div><div className="actions"><a className="darkpill" href={`mailto:${inquiry.email}?subject=${subject}&body=${body}`}>Reply by email</a>{inquiry.phone?<a className="pill" href={`tel:${inquiry.phone}`}>Call {inquiry.phone}</a>:null}</div></div><p className="muted">{inquiry.message}</p><a className="manualLink" href={`mailto:${inquiry.email}`}>{inquiry.email}</a></article>}
