"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { getInquiriesRemote, getListingsRemote, type Inquiry, type Listing } from "../../lib/store";
import { money, prettyDate } from "../../lib/pricing";
import { getSupabaseBrowserClient } from "../../lib/supabase";

type Decision = "AIRBNB" | "WATCH" | "FURNISHED";
type PlanDay = { date: string; decision: Decision; confidence: number; reason: string; monthKey?: string };
type Plan = { days: PlanDay[]; summary?: { headline?: string } } | null;
type MonthRow = { key: string; name: string; rec: Decision; why: string; air: string; furnished: string; days: PlanDay[] };

const sampleMonths: MonthRow[]=[
  {key:"2026-01",name:"Jan",rec:"FURNISHED",why:"Low visitor demand. Use a 30+ day furnished renter.",air:"$900",furnished:"$3,900",days:sampleDays("2026-01",31,"FURNISHED")},
  {key:"2026-02",name:"Feb",rec:"FURNISHED",why:"Short stays are unlikely to fill enough nights.",air:"$1,100",furnished:"$3,900",days:sampleDays("2026-02",28,"FURNISHED")},
  {key:"2026-03",name:"Mar",rec:"WATCH",why:"Leave on Airbnb, but switch if still open 45 days out.",air:"$2,600",furnished:"$3,900",days:sampleDays("2026-03",31,"WATCH")},
  {key:"2026-04",name:"Apr",rec:"AIRBNB",why:"Spring holidays and NYC/Long Island visits support nightly stays.",air:"$4,800",furnished:"$3,900",days:sampleDays("2026-04",30,"AIRBNB")},
  {key:"2026-05",name:"May",rec:"WATCH",why:"Borderline. Watch graduations, weddings, and weekend demand.",air:"$3,400",furnished:"$3,900",days:sampleDays("2026-05",31,"WATCH")},
  {key:"2026-06",name:"Jun",rec:"AIRBNB",why:"Summer Long Island demand supports nightly bookings.",air:"$5,200",furnished:"$4,100",days:sampleDays("2026-06",30,"AIRBNB")},
  {key:"2026-07",name:"Jul",rec:"AIRBNB",why:"Peak summer and July 4th demand. Hold for nightly bookings.",air:"$6,400",furnished:"$4,100",days:sampleDays("2026-07",31,"AIRBNB")},
  {key:"2026-08",name:"Aug",rec:"AIRBNB",why:"Peak summer. Airbnb upside is worth the risk.",air:"$6,100",furnished:"$4,100",days:sampleDays("2026-08",31,"AIRBNB")},
  {key:"2026-09",name:"Sep",rec:"WATCH",why:"Labor Day is strong. The rest of the month may need a switch.",air:"$3,700",furnished:"$4,000",days:sampleDays("2026-09",30,"WATCH")},
  {key:"2026-10",name:"Oct",rec:"FURNISHED",why:"Not enough demand to gamble on scattered weekends.",air:"$1,800",furnished:"$3,900",days:sampleDays("2026-10",31,"FURNISHED")},
  {key:"2026-11",name:"Nov",rec:"WATCH",why:"Thanksgiving may work. Watch the rest of the month.",air:"$2,900",furnished:"$3,900",days:sampleDays("2026-11",30,"WATCH")},
  {key:"2026-12",name:"Dec",rec:"WATCH",why:"Christmas week can work. Avoid leaving the whole month to chance.",air:"$3,200",furnished:"$3,900",days:sampleDays("2026-12",31,"WATCH")}
];

function sampleDays(month:string,count:number,main:Decision):PlanDay[]{return Array.from({length:count},(_,i)=>{const day=String(i+1).padStart(2,"0");let decision=main;if(main==="FURNISHED"&&i>=12&&i<=15)decision="WATCH";if(main==="WATCH"&&i>=23&&i<=26)decision="AIRBNB";return{date:`${month}-${day}`,decision,confidence:decision==="WATCH"?68:82,reason:decision==="AIRBNB"?"Short-stay upside is worth holding for this date.":decision==="WATCH"?"Do not commit yet. Re-check as the date gets closer.":"Long enough and weak enough to market as furnished housing.",monthKey:month}})}

export default function DashboardPage(){
  const [listings,setListings]=useState<Listing[]>([]);
  const [inquiries,setInquiries]=useState<Inquiry[]>([]);
  const [error,setError]=useState("");
  const [userEmail,setUserEmail]=useState<string|null>(null);const [checkingAuth,setCheckingAuth]=useState(true);const [plan,setPlan]=useState<Plan>(null);
  useEffect(()=>{let alive=true;const client=getSupabaseBrowserClient();async function load(){const {data}=client?await client.auth.getSession():{data:{session:null}};if(!alive)return;if(!data.session){setCheckingAuth(false);return}setUserEmail(data.session.user.email||"");try{const [l,i]=await Promise.all([getListingsRemote(),getInquiriesRemote()]);if(alive){setListings(l);setInquiries(i)}}catch(error){if(alive)setError(error instanceof Error?error.message:"Could not load dashboard.")}finally{if(alive)setCheckingAuth(false)}}void load();return()=>{alive=false}},[]);
  useEffect(()=>{const primary=listings.find(l=>l.sourceUrl);if(!primary)return;let alive=true;fetch("/api/calendar-plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sourceUrl:primary.sourceUrl,city:primary.city,state:primary.state,horizonDays:365})}).then(r=>r.json()).then(data=>{if(alive&&data?.ok)setPlan(data.plan)}).catch(()=>{});return()=>{alive=false}},[listings]);
  if(checkingAuth)return <main className="wrap section topspace"><div className="card pad"><p className="muted">Loading your dashboard…</p></div></main>;
  if(!userEmail)return <main className="wrap section topspace"><div className="card pad authCard"><p className="kicker">Calendar CFO dashboard</p><h1 className="big">See what GapStay gives every host.</h1><p className="muted">The dashboard is where your AIRBNB / WATCH / FURNISHED calendar plan lives.</p><CalendarDrilldown plan={null}/><div className="actions"><Link className="darkpill" href="/auth?next=/dashboard">Sign in</Link><Link className="pill" href="/host">Build calendar plan</Link></div></div></main>;
  return <main className="wrap section topspace"><p className="kicker">Calendar CFO dashboard</p><h1 className="big">Your property plan lives here.</h1><p className="muted">Saved calendar plans, monitored properties, alerts, furnished-stay offers, and renter inquiries.</p><div className="actions"><span className="small">Signed in as {userEmail}</span><button className="manualLink buttonLink" onClick={async()=>{await getSupabaseBrowserClient()?.auth.signOut();location.reload()}}>Sign out</button></div>{error?<div className="errorBox">{error}</div>:null}<CalendarDrilldown plan={plan}/><section className="section" style={{paddingTop:28}}><div className="heroCardTop"><h2>Saved plans and offers</h2><Link className="darkpill" href="/host">Build calendar plan</Link></div>{listings.length===0?<div className="card pad" style={{marginTop:16}}><h3>No saved plans yet.</h3><p className="muted">Paste your Airbnb or VRBO listing URL to generate a calendar plan.</p><Link className="darkpill" href="/host">Build calendar plan</Link></div>:<div className="grid" style={{marginTop:16}}>{listings.map(l=><div className="card pad" key={l.id}><div className="heroCardTop"><div><p className="kicker">{publicationLabel(l)}</p><h3>{l.title}</h3><p className="muted">{l.city}, {l.state} · {prettyDate(l.analysis.startDate)} - {prettyDate(l.analysis.endDate)}</p></div><div style={{textAlign:"right"}}><b style={{fontSize:28}}>{money(l.analysis.recommendedTotal)}</b><p className="small">Furnished offer · {money(l.analysis.monthlyEquivalent)}/mo</p></div></div><div className="actions"><Link className="pill" href={`/listing/${l.id}`}>Open offer</Link></div></div>)}</div>}</section><section><h2>Renter inquiries</h2>{inquiries.length===0?<div className="card pad"><p className="muted">No inquiries yet.</p></div>:<div className="grid">{inquiries.map(inquiry=><InquiryCard key={inquiry.id} inquiry={inquiry}/>)}</div>}</section></main>
}

function color(rec:string){return rec==="AIRBNB"?"#7ecfaa":rec==="WATCH"?"#ead27b":"#e87b6a"}
function monthName(key:string){return new Date(`${key}-15T12:00:00`).toLocaleDateString("en-US",{month:"short"})}
function planToMonths(plan:Plan):MonthRow[]{if(!plan?.days?.length)return sampleMonths;const grouped=new Map<string,PlanDay[]>();for(const d of plan.days){const k=d.monthKey||d.date.slice(0,7);grouped.set(k,[...(grouped.get(k)||[]),d])}return Array.from(grouped.entries()).slice(0,12).map(([key,days])=>{const counts={AIRBNB:0,WATCH:0,FURNISHED:0};days.forEach(d=>counts[d.decision]++);const rec=(Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0] as Decision);return{key,name:monthName(key),rec,why:rec==="AIRBNB"?"Most days favor nightly bookings.":rec==="WATCH"?"Mixed month. Click through before deciding.":"Most days favor furnished housing.",air:"—",furnished:"—",days}})}
function CalendarDrilldown({plan}:{plan:Plan}){const rows=useMemo(()=>planToMonths(plan),[plan]);const [selected,setSelected]=useState(rows[0]?.key||"");const month=rows.find(r=>r.key===selected)||rows[0];const [selectedDay,setSelectedDay]=useState<PlanDay|null>(null);useEffect(()=>{if(rows[0]&&!rows.find(r=>r.key===selected))setSelected(rows[0].key)},[rows,selected]);return <section className="card pad" style={{margin:"22px 0"}}><div className="heroCardTop"><div><p className="kicker">Calendar plan</p><h2>{plan?"Live plan from saved listing":"Massapequa, NY sample plan"}</h2><p className="muted">Click a month to see the actual days inside it. Short furnished-stay islands are suppressed unless the gap is long enough to pursue a tenant.</p></div><div className="result"><SmallLegend color="#7ecfaa" label="AIRBNB"/><SmallLegend color="#ead27b" label="WATCH"/><SmallLegend color="#e87b6a" label="FURNISHED"/></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:16,marginTop:18}}>{rows.map(m=><button key={m.key} type="button" onClick={()=>{setSelected(m.key);setSelectedDay(null)}} className="stat" style={{textAlign:"left",borderLeft:`6px solid ${color(m.rec)}`,minWidth:0,outline:m.key===month.key?"2px solid rgba(17,17,17,.25)":"none"}}><span>{m.name}</span><strong style={{fontSize:16,whiteSpace:"nowrap",lineHeight:1.1}}>{m.rec}</strong><p className="small" style={{margin:"8px 0"}}>{m.why}</p>{m.air!=="—"?<p className="small" style={{margin:0}}>Airbnb likely: <b>{m.air}</b><br/>Furnished: <b>{m.furnished}</b></p>:<p className="small" style={{margin:0}}>Days: <b>{m.days.length}</b></p>}</button>)}</div>{month?<div className="card pad" style={{marginTop:18,background:"#fbf7ef"}}><div className="heroCardTop"><div><p className="kicker">{month.name} day view</p><h3>{month.rec} month, with day-level detail</h3></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(7,minmax(34px,1fr))",gap:6,marginTop:14}}>{month.days.map(d=><button key={d.date} type="button" title={`${d.date}: ${d.decision}`} onClick={()=>setSelectedDay(d)} style={{border:"1px solid rgba(17,17,17,.12)",borderRadius:8,padding:"8px 4px",background:color(d.decision),fontWeight:700,cursor:"pointer"}}>{Number(d.date.slice(-2))}</button>)}</div>{selectedDay?<div className="successBox" style={{marginTop:16}}><strong>{selectedDay.date}: {selectedDay.decision}</strong><br/>{selectedDay.confidence}% confidence. {selectedDay.reason}</div>:<p className="small" style={{marginTop:12}}>Tap any day to see the reason and confidence score.</p>}</div>:null}<div className="successBox" style={{marginTop:18}}><strong>Next action:</strong> Use the month view to decide strategy, then open the day view before committing to a furnished tenant.</div></section>}
function SmallLegend({color,label}:{color:string;label:string}){return <span className="small" style={{display:"inline-flex",alignItems:"center",gap:6,marginRight:10,whiteSpace:"nowrap"}}><span style={{width:10,height:10,borderRadius:99,background:color}}/>{label}</span>}
function publicationLabel(listing:Listing){if(listing.publishStatus!=="published") return "Plan preview";if(!listing.paidUntil) return "Published furnished-stay offer";const days=Math.max(0,Math.ceil((new Date(listing.paidUntil).getTime()-Date.now())/86400000));return `Published offer · ${days} ${days===1?"day":"days"} remaining`}
function InquiryCard({inquiry}:{inquiry:Inquiry}){const subject=encodeURIComponent("Your furnished-stay inquiry");const body=encodeURIComponent(`Hi ${inquiry.name},\n\nThanks for your inquiry. I’d be happy to discuss the furnished stay and your dates.\n\n`);return <article className="card pad"><div className="heroCardTop"><div><p className="kicker">{inquiry.reason||"New inquiry"}</p><h3>{inquiry.name}</h3><p className="small">Received {new Date(inquiry.createdAt).toLocaleDateString()}</p></div><div className="actions"><a className="darkpill" href={`mailto:${inquiry.email}?subject=${subject}&body=${body}`}>Reply by email</a>{inquiry.phone?<a className="pill" href={`tel:${inquiry.phone}`}>Call {inquiry.phone}</a>:null}</div></div><p className="muted">{inquiry.message}</p><a className="manualLink" href={`mailto:${inquiry.email}`}>{inquiry.email}</a></article>}
